templates:
  options:
    module: 'frmwrk.templates'
  src: 'src/app/**/*.jade'
  dest: 'src/app/templates.js'
common:
  options:
    module: 'frmwrk.common'
  src: 'src/common/**/*.jade'
  dest: 'src/app/common.js'