app:
  options:
    module: 'frmwrk.app.tpl'
  src: 'src/app/**/*.jade'
  dest: 'src/app/app.tpl.js'
common:
  options:
    module: 'frmwrk.common.tpl'
  src: 'src/common/**/*.jade'
  dest: 'src/app/common.tpl.js'