index:
  files: 'src/static/tpl/index.jade'
  tasks: 'jade:index'
  options:
    livereload: true
app:
  files: 'src/app/**/*.jade'
  tasks: 'html2js:app'
  options:
    livereload: true
common:
  files: 'src/common/**/*.jade'
  tasks: 'html2js:common'
  options:
    livereload: true
less:
  files:
    - 'src/static/**/*.less'
    - 'src/app/**/*.less'
    - 'src/common/**/*.less'
  tasks: 'less:build'
  options:
    livereload: true
js:
  files: 'src/**/*.js'
  tasks: 'browserify:build'
  options:
    livereload: true